services:
  - type: web
    name: playwright-flask
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
