services:
  - type: web
    name: selenium-cloudflare
    env: debian
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
